# Generated by Django 5.2 on 2025-04-04 12:26

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if flat.owner:
            Owner.objects.get_or_create(
                full_name=flat.owner,
                phone_number=flat.owners_phonenumber,
                normalized_phone=flat.owner_pure_phone
            )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
