# Generated by Django 5.2 on 2025-04-04 12:50

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if flat.owner:
            owner, _ = Owner.objects.get_or_create(
                full_name=flat.owner,
                phone_number=flat.owners_phonenumber,
                normalized_phone=flat.owner_pure_phone
            )
            owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20250404_1726'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners),
    ]
