# Generated by Django 5.2 on 2025-04-07 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_alter_complaint_flat_alter_complaint_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
    ]
